format = """
$directory\
$git_branch\
$git_status \
$character\
"""

add_newline       = false

[character]
success_symbol    = "[\\$](fg:#83a598)"
error_symbol      = "[\\$](bold fg:#cc241d)"
vimcmd_symbol     = "[\\$](fg:#b8bb26)"

[directory]
format            = "[$path]($style)[$read_only]($read_only_style)"
style             = "bold fg:#d3869b"
read_only_style   = "bold fg:#d3869b"
read_only         = " "
truncation_symbol = "…/"

[git_branch]
symbol            = ""
style             = "bold fg:#8ec07c"
format            = " on [$symbol $branch]($style)"

[git_status]
style             = "italic bold fg:#8ec07c"
format            = "[$all_status$ahead_behind]($style)"
conflicted        = " ?"
untracked         = " ~"
stashed           = " "
modified          = " "
staged            = " +$count"
renamed           = " 凜"
deleted           = " 﫧"
ahead             = "  ${count}"
diverged          = " ﰵ ${ahead_count}  ${behind_count}"
behind            = "  ${count}"
