format = """
$directory\
[](#fabd2f)\
$git_branch\
$git_status\
$git_metrics\
$fill\
[](fg:#d3869b)\
[ ](bg:#d3869b)\
$shell\
[ ](bg:#d3869b)\
[](bg:#d3869b fg:#8ec07c)\
$username\
[](bg:#8ec07c fg:#83a598)\
$time\
[](fg:#33658a)\
[\n](fg:#33658a)\
[  ](fg:#83a598)\
"""

add_newline          = true

[fill]
symbol               = " "

[username]
show_always          = true
style_user           = "bg:#8ec07c fg:#282828"
style_root           = "bg:#8ec07c fg:#282828"
format               = '[ $user ]($style)'

[directory]
format               = "[ ](bg:#fabd2f)[$path]($style)[ ](bg:#fabd2f)[$read_only]($read_only_style)"
style                = "bg:#fabd2f fg:#282828"
read_only            = " "
read_only_style      = "bg:#fabd2f fg:#282828"
truncation_symbol    = "…/"
truncation_length    = 8

[git_status]
style                = "bg:#fb4934"
format               = "[[($all_status$ahead_behind )](bg:#fb4934 fg:#282828)]($style)"
conflicted           = " ? "
untracked            = " ~ "
stashed              = "  "
modified             = " ! "
staged               = " ++$count "
renamed              = " 凜 "
deleted              = " 﫧 "
ahead                = "  ${count}"
diverged             = " ﰵ ${ahead_count}  ${behind_count}"
behind               = "  ${count}"

[git_branch]
symbol               = ""
style                = "bg:#fb4934"
format               = '[](bg:#fb4934 fg:#282828)[[ $symbol $branch ](bg:#fb4934 fg:#282828)]($style)'

[shell]
disabled             = false
format               = "[$indicator]($style)"
style                = "bg:#d3869b fg:#282828"
bash_indicator       = "bash"
fish_indicator       = "fish"
zsh_indicator        = "zsh"
powershell_indicator = "psh"
ion_indicator        = "ion"
elvish_indicator     = "esh"
tcsh_indicator       = "tsh"
xonsh_indicator      = "xsh"
cmd_indicator        = "cmd"
nu_indicator         = "nu"
unknown_indicator    = "?"

[time]
disabled             = false
time_format          = "%T"
style                = "bg:#83a598"
format               = '[[ $time ](bg:#83a598 fg:#282828)]($style)'

[git_metrics]
disabled             = false
only_nonzero_diffs   = false
added_style          = "bg:#3c3836 fg:#b8bb26"
deleted_style        = "bg:#3c3836 fg:#fb4934"
format               = '[ ](bg:#3c3836 fg:#fb4934)[+$added ]($added_style)[-$deleted ]($deleted_style)[](fg:#3c3836)'
