format = """
$directory\
$git_branch\
$git_status \
[](fg:#83a598) \
"""

add_newline = false

[directory]
format            = "[$path]($style)[$read_only]($read_only_style)"
style             = "fg:#d3869b"
read_only         = " "
read_only_style   = "fg:#d3869b"
truncation_symbol = "../"

[git_branch]
symbol            = ""
style             = "fg:#8ec07c"
format            = " on [$symbol $branch]($style)"

[git_status]
style             = "fg:#8ec07c"
format            = "[$all_status$ahead_behind]($style)"
conflicted        = " ?"
untracked         = " ~"
stashed           = " "
modified          = " !"
staged            = " +$count"
renamed           = " 凜"
deleted           = " 﫧"
ahead             = "  ${count}"
diverged          = " ﰵ ${ahead_count}  ${behind_count}"
behind            = "  ${count}"
