require "user.blankline"
require "user.cmp"
require "user.colorschemes"
require "user.gitgutter"
require "user.keymaps"
require "user.lualine"
require "user.neo-tree"
require "user.options"
require "user.plugins"
require "user.treesitter"
require "user.lsp"
-- require "user.telescope"
require "user.toggleterm"
require "user.bufferline"
